version: "3.9"

services:
  bot:
    build: .
    container_name: agent-liuba-bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/main.py"]
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
      - ./conversations:/app/conversations
      - ./data:/app/data
      - ~/.cache/huggingface:/root/.cache/huggingface  # кэш моделей sentence-transformers
    networks:
      - agent_net

networks:
  agent_net:
    driver: bridge


